# development build

KVERSION = $(shell uname -r)
KDIR := /lib/modules/$(KVERSION)/build
PWD := $(shell pwd)

CONFIG_HID_LG4L := m
CONFIG_HID_LG4L_G13= m
CONFIG_HID_LG4L_G15 := m
CONFIG_HID_LG4L_G15v2 := m
CONFIG_HID_LG4L_G19 := m
CONFIG_HID_LG4L_G110 := m

export CONFIG_HID_LG4L
export CONFIG_HID_LG4L_G13
export CONFIG_HID_LG4L_G15
export CONFIG_HID_LG4L_G15v2
export CONFIG_HID_LG4L_G19
export CONFIG_HID_LG4L_G110



default:
	$(MAKE) -C $(KDIR) M=$(PWD)

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

install:
	$(MAKE) -C $(KDIR) M=$(PWD) modules_install

TAGS:
	$(MAKE) -C $(KDIR) M=$(PWD) TAGS
